---
title: "classification_tree"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r}
library(dplyr)
library(caret)
library(ggplot2)
library(tidyverse)
```


```{r}
setwd('/Users/yingchenliu/Desktop/university/stat149/stat149_final_project/data')
member = read.csv('member-data-2020-stat149.csv')


## MISSING VALUES

# Convert yes/no vars with no missing values to 1/0
member$AnySection = as.numeric(as.factor(member$AnySection))-1
member$DontPublish = as.numeric(as.factor(member$DontPublish))-1
member$InChapter = as.numeric(as.factor(member$InChapter))-1
member$P.SEC.BE = as.numeric(as.factor(member$P.SEC.BE))-1
member$P.SEC.BIOM = as.numeric(as.factor(member$P.SEC.BIOM))-1
member$P.SEC.BIOP = as.numeric(as.factor(member$P.SEC.BIOP))-1
member$P.SEC.CNSL = as.numeric(as.factor(member$P.SEC.CNSL))-1
member$P.SEC.COMP = as.numeric(as.factor(member$P.SEC.COMP))-1
member$P.SEC.EDUC = as.numeric(as.factor(member$P.SEC.EDUC))-1
member$P.SEC.ENVR = as.numeric(as.factor(member$P.SEC.ENVR))-1
member$P.SEC.EPI = as.numeric(as.factor(member$P.SEC.EPI))-1
member$P.SEC.GOVT = as.numeric(as.factor(member$P.SEC.GOVT))-1
member$P.SEC.GRPH = as.numeric(as.factor(member$P.SEC.GRPH))-1
member$P.SEC.HPSS = as.numeric(as.factor(member$P.SEC.HPSS))-1
member$P.SEC.MDD = as.numeric(as.factor(member$P.SEC.MDD))-1
member$P.SEC.MHS = as.numeric(as.factor(member$P.SEC.MHS))-1
member$P.SEC.MKTG = as.numeric(as.factor(member$P.SEC.MKTG))-1
member$P.SEC.NPAR = as.numeric(as.factor(member$P.SEC.NPAR))-1
member$P.SEC.QP = as.numeric(as.factor(member$P.SEC.QP))-1
member$P.SEC.SBSS = as.numeric(as.factor(member$P.SEC.SBSS))-1
member$P.SEC.SDNS = as.numeric(as.factor(member$P.SEC.SDNS))-1
member$P.SEC.SGG = as.numeric(as.factor(member$P.SEC.SGG))-1
member$P.SEC.SI = as.numeric(as.factor(member$P.SEC.SI))-1
member$P.SEC.SIS = as.numeric(as.factor(member$P.SEC.SIS))-1
member$P.SEC.SLDM = as.numeric(as.factor(member$P.SEC.SLDM))-1
member$P.SEC.SOC = as.numeric(as.factor(member$P.SEC.SOC))-1
member$P.SEC.SPES = as.numeric(as.factor(member$P.SEC.SPES))-1
member$P.SEC.SRMS = as.numeric(as.factor(member$P.SEC.SRMS))-1
member$P.SEC.SSPA = as.numeric(as.factor(member$P.SEC.SSPA))-1
member$P.SEC.TSHS = as.numeric(as.factor(member$P.SEC.TSHS))-1

# Convert MEMTYPE to a factor variable
member$MEMTYPE = as.factor(member$MEMTYPE)

# Impute missing values of USA.CAN with the mean (most frequent binary obs)
table(member$USA.CAN)
member$USA.CAN = as.numeric(as.factor(member$USA.CAN))-1
member$USA.CAN[is.na(member$USA.CAN )] = 1

# Convert Gender and EmploymentCategory to factors with NA level
setwd('/Users/yingchenliu/Desktop/university/stat149/stat149_final_project')
source("na-convert.R")
member$Gender = as.factor(member$Gender)
member$EmploymentCategory = as.factor(member$EmploymentCategory)

# Handling other missing variables via na.convert.mean
member= na.convert.mean(member)

# create one extra column
head(member)

```



```{r}
# Handle Outliers of Age
member = member[member$Age <101,]
member = member[member$Age >15, ]
member = member[member$AgeJoinedASA<90, ]
member = member[member$AgeJoinedASA>15, ]
dim(member)
```

```{r}
library(regclass)

 SL <- suggest_levels(AnySection ~ MEMTYPE,data=member,target=4,recode=TRUE)
	SL$Conversion
	member$MEMTYPE_new <- SL$newlevels
```


```{r}
## 75% of the sample size
smp_size <- floor(0.75 * nrow(member))

## set the seed to make your partition reproducible
set.seed(149)
train_ind <- sample(seq_len(nrow(member)), size = smp_size)

train <- member[train_ind, ]
test <- member[-train_ind, ]

write.csv(train,"data/train_data.csv", row.names = FALSE)
write.csv(test,"data/test_data.csv", row.names = FALSE)
write.csv(member,"data/full_data.csv", row.names = FALSE)
```

```{r}
library(rpart)
library(rpart.plot)

```


## Load data
```{r}
full = read_csv('data/full_data.csv',  na=character())
train_data = read_csv('data/train_data.csv',  na=character())
test_data = read_csv('data/test_data.csv',  na=character())
```

```{r}
dim(train_data)
dim(test_data)
```
```{r}
summary(full$Gender)
table(train$Gender)
```


```{r}
head(train_data)
```


```{r}
# Fit a binary classification tree with cp=0.001
member.tree.full = rpart(AnySection ~ .,
cp=0.001, data=train_data, method="class", parms=list(split="information"))
png(file="tree_full.png",
    width=11, height=8.5, units="in", res=300)
prp(member.tree.full,type=0,extra=106,digits=0,
main= "Classification Tree (Full Model)")

# Use plotcp to see the CV results graphically
plotcp(member.tree.full)
# Prune the tree based on cp=0.0037
member.pruned = prune(member.tree.full, cp=0.0037)
png(file="rpart_pruned_cp=0.0037.png",
    width=11, height=8.5, units="in", res=300)
prp(member.pruned,type=0,extra=106,digits=0,
main= "Classification Tree Pruned cp=0.0037.png")

# Predict on the test set and get confusion matrix (test accuracy: 0.6911)
tree_pred_test = predict(member.pruned, test_data)[,2]
confusionMatrix(data=factor(as.numeric(tree_pred_test>=0.5)), 
                reference=factor(test_data$AnySection), positive="1")
```

```{r}
member.pruned
```


```{r}
library(rpart)
library(rpart.plot)

# Load data
setwd('/Users/yingchenliu/Desktop/university/stat149/stat149_final_project/data')
full = read_csv('full_data.csv',  na=character())
train_data = read_csv('train_data.csv',  na=character())
test_data = read_csv('test_data.csv',  na=character())

dim(train_data)
dim(test_data)

summary(full$Gender)
table(train$Gender)

member.tree.full = rpart(AnySection ~ .,
                         cp=0.001, data=train_data, method="class", parms=list(split="information"))

png(file="tree_full.png",
    width=11, height=8.5, units="in", res=300)
prp(member.tree.full,type=0,extra=106,digits=0,
    main= "Classification Tree (Full Model)")
dev.off()

# Use plotcp to see the CV results graphically
png(file="plotcp.png",
    width=11, height=8.5, units="in", res=300)
plotcp(member.tree.full)
dev.off()


# Prune the tree based on cp=0.0037
member.pruned = prune(member.tree.full, cp=0.0037)
png(file="rpart_pruned_cp=0.0037.png",
    width=11, height=8.5, units="in", res=300)
prp(member.pruned,type=0,extra=106,digits=0,
    main= "Classification Tree Pruned cp=0.0037.png")
dev.off()


# Predict on the test set and get confusion matrix (test accuracy: 0.7001)
tree_pred_test = predict(member.pruned, test_data)[,2]
confusionMatrix(data=factor(as.numeric(tree_pred_test>=0.5)), 
                reference=factor(test_data$AnySection), positive="1")


```

